const input=document.getElementById('archiveSearch');
const results=document.getElementById('searchResults');
const summary=document.getElementById('searchSummary');
const filters=[...document.querySelectorAll('.search-filter')];
let activeFilter='all';let archiveIndex=[];
function norm(v){return String(v||'').toLowerCase().normalize('NFKD').replace(/[^a-z0-9\s-]/g,' ')}
function score(item,words,full){const title=norm(item.title),tags=norm((item.tags||[]).join(' ')),meta=norm(item.meta),summaryText=norm(item.summary);let total=0;if(full&&title===full)total+=100;if(full&&title.includes(full))total+=35;for(const word of words){if(title.includes(word))total+=12;if(tags.includes(word))total+=7;if(meta.includes(word))total+=4;if(summaryText.includes(word))total+=2}return total}
function render(){const raw=input.value.trim(),q=norm(raw),words=q.split(/\s+/).filter(Boolean);const matches=archiveIndex.filter(item=>{if(activeFilter!=='all'&&item.type!==activeFilter)return false;const hay=norm(`${item.title} ${item.meta} ${item.summary} ${(item.tags||[]).join(' ')}`);return words.every(w=>hay.includes(w))}).map((item,index)=>({item,index,score:score(item,words,q)})).sort((a,b)=>b.score-a.score||a.index-b.index).map(x=>x.item);summary.textContent=q?`${matches.length} result${matches.length===1?'':'s'} for “${raw}”`:`Showing ${matches.length} indexed routes, speakers, committees and source records.`;results.innerHTML=matches.map(item=>`<a class="card search-result" href="${item.url}"${item.url.startsWith('http')?' target="_blank" rel="noreferrer"':''}><span class="type">${item.type}</span><div><h3>${item.title}</h3><p><strong>${item.meta}</strong> · ${item.summary}</p></div><b>→</b></a>`).join('')||'<article class="card section-card"><h3>No indexed result</h3><p>Try a person, date, committee, theme or constitutional idea.</p></article>'}
filters.forEach(btn=>btn.addEventListener('click',()=>{filters.forEach(b=>b.classList.remove('active'));btn.classList.add('active');activeFilter=btn.dataset.filter;render()}));input.addEventListener('input',render);document.addEventListener('keydown',e=>{if(e.key==='/'&&document.activeElement!==input){e.preventDefault();input.focus()}if(e.key==='Escape'&&document.activeElement===input){input.value='';render();input.blur()}});
async function loadJson(url){const response=await fetch(url,{cache:'no-store'});if(!response.ok)throw new Error(`${url}: HTTP ${response.status}`);return response.json()}
async function bootSearch(){summary.textContent='Loading prepared archive index…';try{const manifest=await loadJson('data/search-manifest.json');if(!Array.isArray(manifest.sources)||!manifest.sources.length)throw new Error('Search manifest has no sources');const indexes=await Promise.all(manifest.sources.map(loadJson));archiveIndex=indexes.flat();const params=new URLSearchParams(location.search);if(params.get('q'))input.value=params.get('q');render()}catch(error){console.error('Archive search index failed to load',error);summary.textContent='Search index could not be loaded.';results.innerHTML='<article class="card section-card"><h3>Search temporarily unavailable</h3><p>The archive pages and source index remain accessible through navigation.</p></article>'}}
bootSearch();