const input=document.getElementById('archiveSearch');
const results=document.getElementById('searchResults');
const summary=document.getElementById('searchSummary');
const filters=[...document.querySelectorAll('.search-filter')];
let activeFilter='all';let archiveIndex=[];
function norm(v){return String(v||'').toLowerCase().normalize('NFKD').replace(/[^a-z0-9\s-]/g,' ')}
function render(){const q=norm(input.value.trim());const words=q.split(/\s+/).filter(Boolean);const matches=archiveIndex.filter(item=>{if(activeFilter!=='all'&&item.type!==activeFilter)return false;const hay=norm(`${item.title} ${item.meta} ${item.summary} ${(item.tags||[]).join(' ')}`);return words.every(w=>hay.includes(w))});summary.textContent=q?`${matches.length} result${matches.length===1?'':'s'} for “${input.value.trim()}”`:`Showing ${matches.length} indexed routes, speakers and source records.`;results.innerHTML=matches.map(item=>`<a class="card search-result" href="${item.url}"${item.url.startsWith('http')?' target="_blank" rel="noreferrer"':''}><span class="type">${item.type}</span><div><h3>${item.title}</h3><p><strong>${item.meta}</strong> · ${item.summary}</p></div><b>→</b></a>`).join('')||'<article class="card section-card"><h3>No indexed result</h3><p>Try a person, date, theme or constitutional idea.</p></article>'}
filters.forEach(btn=>btn.addEventListener('click',()=>{filters.forEach(b=>b.classList.remove('active'));btn.classList.add('active');activeFilter=btn.dataset.filter;render()}));input.addEventListener('input',render);document.addEventListener('keydown',e=>{if(e.key==='/'&&document.activeElement!==input){e.preventDefault();input.focus()}});
async function loadIndex(url){const response=await fetch(url,{cache:'no-store'});if(!response.ok)throw new Error(`${url}: HTTP ${response.status}`);return response.json()}
async function bootSearch(){summary.textContent='Loading prepared archive index…';try{const sources=['data/search-index.json','data/search-speakers-granular.json','data/search-session-1946-12-19.json','data/search-speakers-1946-12-19.json','data/search-session-1946-12-21.json','data/search-speakers-1946-12-21.json','data/search-session-1946-12-23.json','data/search-speakers-1946-12-23.json','data/search-session-1947-01-20.json','data/search-speakers-1947-01-20.json'];const indexes=await Promise.all(sources.map(loadIndex));archiveIndex=indexes.flat();const params=new URLSearchParams(location.search);if(params.get('q'))input.value=params.get('q');render()}catch(error){console.error('Archive search index failed to load',error);summary.textContent='Search index could not be loaded.';results.innerHTML='<article class="card section-card"><h3>Search temporarily unavailable</h3><p>The archive pages and source index remain accessible through navigation.</p></article>'}}
bootSearch();