import fs from 'node:fs';
import path from 'node:path';
import {spawnSync} from 'node:child_process';

const root=process.cwd();
const skipDirs=new Set(['.git','.github','node_modules']);
const bannedPublicVisuals=[
  'assembly-hall-panorama.svg','objectives-resolution-visual.svg','rajendra-prasad-engraved.svg','ambedkar-engraved.svg','sachchidananda-sinha-caricature.svg',
  'rajendra-prasad-archival.jpg','br-ambedkar-archival-1946.jpg','sachchidananda-sinha-illustrated.webp','jb-kripalani-illustrated.webp','nehru-illustrated.webp'
];
function walk(dir){const out=[];for(const entry of fs.readdirSync(dir,{withFileTypes:true})){if(entry.isDirectory()&&skipDirs.has(entry.name))continue;const full=path.join(dir,entry.name);if(entry.isDirectory())out.push(...walk(full));else out.push(full)}return out}
const files=walk(root),htmlFiles=files.filter(f=>f.endsWith('.html')),jsonFiles=files.filter(f=>f.endsWith('.json')),svgFiles=files.filter(f=>f.endsWith('.svg')),jsFiles=files.filter(f=>f.endsWith('.js')),failures=[],checked=[];
function rel(file){return path.relative(root,file).split(path.sep).join('/')}
function isExternal(v){return /^(?:https?:|mailto:|tel:|javascript:|data:|\/\/)/i.test(v)}
function resolveLocal(sourceFile,rawValue){const value=rawValue.trim();if(!value||value==='#'||value.startsWith('#')||isExternal(value))return null;const clean=decodeURIComponent(value.split('#')[0].split('?')[0]);if(!clean)return null;if(clean.startsWith('/'))return path.join(root,clean.replace(/^\/+/,''));return path.resolve(path.dirname(sourceFile),clean)}
for(const htmlFile of htmlFiles){const html=fs.readFileSync(htmlFile,'utf8');for(const match of html.matchAll(/\b(?:href|src|data-granular-session)\s*=\s*["']([^"']+)["']/gi)){const raw=match[1],target=resolveLocal(htmlFile,raw);if(!target)continue;let candidate=target;if(fs.existsSync(candidate)&&fs.statSync(candidate).isDirectory())candidate=path.join(candidate,'index.html');checked.push(`${rel(htmlFile)} -> ${raw}`);if(!fs.existsSync(candidate))failures.push(`${rel(htmlFile)} references missing local target: ${raw}`)}for(const asset of bannedPublicVisuals){if(html.includes(asset))failures.push(`${rel(htmlFile)} publicly references retired visual asset: ${asset}`)}}
let portraitNames=new Set();
for(const jsonFile of jsonFiles){try{const raw=fs.readFileSync(jsonFile,'utf8');for(const asset of bannedPublicVisuals){if(raw.includes(asset))failures.push(`${rel(jsonFile)} references retired public visual asset: ${asset}`)}const data=JSON.parse(raw);if(rel(jsonFile)==='assets/portraits/manifest.json'){if(!data.portraits||typeof data.portraits!=='object')failures.push('Portrait manifest must contain a portraits object');else{portraitNames=new Set(Object.keys(data.portraits));if(portraitNames.size<100)failures.push('Portrait manifest unexpectedly contains fewer than 100 indexed personalities')}}if(rel(jsonFile)==='data/search-manifest.json'){if(!Array.isArray(data.sources)||!data.sources.length)failures.push('Search manifest must contain a non-empty sources array');else for(const source of data.sources){if(!fs.existsSync(path.join(root,source)))failures.push(`Search manifest references missing source: ${source}`)}}if(rel(jsonFile).startsWith('data/session-')&&data.editorialStatus==='granular-speaker-timeline-live'){if(!data.session?.primarySource?.recordUrl)failures.push(`${rel(jsonFile)} granular reader must link the official Parliament record`);if(!data.session?.primarySource?.fileName)failures.push(`${rel(jsonFile)} granular reader must include the official PDF filename for the embedded source reader`);if(!Array.isArray(data.speakers)||data.speakers.length<2)failures.push(`${rel(jsonFile)} granular session must include a speakers array`);if(!Array.isArray(data.interventions)||data.interventions.length<3)failures.push(`${rel(jsonFile)} granular session must include an interventions array`);const ids=new Set((data.speakers||[]).map(s=>s.id));for(const item of data.interventions||[]){if(!ids.has(item.speakerId))failures.push(`${rel(jsonFile)} intervention ${item.id||'(unnamed)'} references unknown speakerId ${item.speakerId}`);if(!item.paragraphRef)failures.push(`${rel(jsonFile)} intervention ${item.id||'(unnamed)'} is missing paragraphRef`);if(!item.summary)failures.push(`${rel(jsonFile)} intervention ${item.id||'(unnamed)'} is missing summary`)}}}catch(error){failures.push(`${rel(jsonFile)} is invalid JSON: ${error.message}`)}}
for(const jsFile of jsFiles){const check=spawnSync(process.execPath,['--check',jsFile],{encoding:'utf8'});if(check.status!==0)failures.push(`${rel(jsFile)} has JavaScript syntax errors: ${(check.stderr||check.stdout||'unknown error').trim()}`)}
for(const svgFile of svgFiles){const svg=fs.readFileSync(svgFile,'utf8');if(!svg.includes('<svg'))failures.push(`${rel(svgFile)} is not valid SVG markup`);if(!svg.includes('<title'))failures.push(`${rel(svgFile)} is missing an accessible <title>`)}
const corePortraits=['sachchidananda-sinha','rajendra-prasad','br-ambedkar','jawaharlal-nehru','jb-kripalani','sarvepalli-radhakrishnan','km-munshi','syama-prasad-mookerjee','alladi-krishnaswami-ayyar','hansa-mehta'].map(id=>`assets/portraits/${id}.webp`);
const required=['index.html','home.css','ux.css','chronology.html','chronology.js','committees.html','committees.css','speakers.html','speakers.css','speakers.js','themes.html','documents.html','provisions.html','provisions.css','provisions.js','visual-atlas.html','search.html','search.js','portrait-pending.css','session-granular.css','session-granular.js','session-nav.css','session-nav.js','styles.css','visuals.css','app.js','VISUAL_ASSET_POLICY.md','PORTRAIT_STANDARD.md','THIRD_PARTY_NOTICES.md','assets/portraits/manifest.json','scripts/sync-portrait-manifest.mjs','scripts/sync-search-manifest.mjs','scripts/check-indexes.mjs','scripts/check-genealogy.mjs','data/search-manifest.json','data/provision-genealogy.json','data/search-provisions.json','data/search-speakers-profiles.json','assets/constitution-hall-generated.png',...corePortraits,'sessions/1946-12-09.html','sessions/1946-12-10.html','sessions/1946-12-11.html','sessions/1946-12-12.html','sessions/1946-12-13.html','sessions/1946-12-16.html','sessions/1946-12-17.html','sessions/1946-12-18.html','sessions/1946-12-19.html','sessions/1946-12-21.html','sessions/1946-12-23.html','sessions/1947-01-20.html','sessions/1947-01-21.html','sessions/1947-01-22.html','sessions/1947-01-24.html','sessions/1947-01-25.html','sessions/1947-04-28.html','sessions/1947-04-29.html','sessions/1947-04-30.html','sessions/1947-05-01.html','speakers/sachchidananda-sinha.html','speakers/rajendra-prasad.html','speakers/br-ambedkar.html','speakers/jb-kripalani.html','speakers/jawaharlal-nehru.html','speakers/sarvepalli-radhakrishnan.html','speakers/syama-prasad-mookerjee.html','speakers/km-munshi.html','topics/rules-procedure.html','topics/objectives-resolution.html','topics/fundamental-rights.html','topics/indian-states-union.html','data/session-1946-12-13.json','data/session-1946-12-16.json','data/session-1946-12-17.json','data/session-1946-12-18.json','data/session-1946-12-19.json','data/session-1946-12-21.json','data/session-1946-12-23.json','data/session-1947-01-20.json','data/session-1947-01-21.json','data/session-1947-01-22.json','data/session-1947-01-24.json','data/session-1947-01-25.json','data/session-1947-04-28.json','data/search-index.json','data/search-committees.json','data/search-speakers-granular.json'];
for(const item of required){if(!fs.existsSync(path.join(root,item)))failures.push(`Required site file missing: ${item}`)}
for(const asset of ['assets/constitution-hall-generated.png',...corePortraits]){const file=path.join(root,asset);if(fs.existsSync(file)&&fs.statSync(file).size<10000)failures.push(`${asset} is unexpectedly small or empty`)}
if(failures.length){console.error('\nStatic archive integrity check FAILED:\n');for(const failure of failures)console.error(`  - ${failure}`);console.error(`\nChecked ${htmlFiles.length} HTML files, ${jsonFiles.length} JSON files, ${jsFiles.length} JavaScript files, ${svgFiles.length} SVG files and ${checked.length} local references.`);process.exit(1)}
console.log(`Static archive integrity check passed: ${htmlFiles.length} HTML files, ${jsonFiles.length} JSON files, ${jsFiles.length} JavaScript files, ${svgFiles.length} SVG files, ${checked.length} local references, ${required.length} required routes/assets, ${portraitNames.size} portrait names registered.`);
